name: Audit Log
on:
  pull_request:
    types:
      - closed

jobs:
  pr_merged_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: |
          git config --global --add safe.directory $(realpath .)
          echo "Pull Request #${{ github.event.pull_request.number }} was merged."  >> audit.log
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Published Changes"
          git push
